services:
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: unahur
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  
  usuario:
    image: mongo-express
    ports:
      - "8082:8081"
    environment:
      MONGO_INITDB_ROOT_ADMIN_USERNAME: root
      MONGO_INITDB_ROOT_ADMIN_PASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database:27017/
      ME_CONFIG_BASICAUTH: false

  api:
    build: .
    ports:
      - "5000:4001"
    environment:
      - PORT=4001
      - MONGO_URL=mongodb://root:example@database:27017/unahur?authSource=admin
      - CANTIDAD_MAX_MESES:6
    depends_on:
      - database